---
dns_adblock_lists_defaults: []
dns_adblock_lists_extras: []
dns_adblock_lists: "{{ dns_adblock_lists_defaults + dns_adblock_lists_extras }}"

# Often blocklists contain these IPs. We want to remove them from our lists
dns_replace_address:
  - '127.0.0.1'
  - '0.0.0.0'

# List of extra domains to block, in addition to what we have listed
# in `dns_adblock_lists`
# Example:
# dns_adblock_lists_custom:
#   - type: adblock
#     content: |
#       ...
dns_adblock_lists_custom: []
